# Generated by Django 5.1.1 on 2024-09-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PotholeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_description", models.TextField(default="N/A")),
                ("alternate_description", models.TextField(default="N/A")),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "town_name",
                    models.CharField(
                        blank=True, default="Unknown Town", max_length=255
                    ),
                ),
                (
                    "road_type",
                    models.CharField(
                        blank=True, default="Unknown Road Type", max_length=255
                    ),
                ),
                (
                    "road_name",
                    models.CharField(
                        blank=True, default="Unnamed Road", max_length=255
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "video_url",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
