# Generated by Django 5.1.1 on 2024-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potholereport",
            name="destination",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="potholereport",
            name="origin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
