# Generated by Django 5.1.1 on 2024-09-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_alter_potholereport_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="potholereport",
            name="location_lat",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="potholereport",
            name="location_lon",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="potholereport",
            name="road_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="potholereport",
            name="road_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="potholereport",
            name="town_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
